//! v5-γ stage 2 schema cache.
//!
//! Sidekick file persisted alongside the relon-object-cache ET_DYN +
//! the legacy IR cache. The schema cache holds the bits of context the
//! buffer-protocol trampoline needs that the object cache does not
//! already expose: the canonical main / return schemas, the const-data
//! blob, the entry shape + range, parameter names, and the closure
//! count. Without these, the dlopen-exec hot path would need to
//! re-parse + re-analyze the source on every cold start (~50-100 µs),
//! which blows the v5-γ stage 2 strict-mode budget of ≤ 15 µs.
//!
//! ## File layout (v2)
//!
//! Filename: `<source_hash>.relon-schema-v1`, alongside
//! `<source_hash>.relon-native-v1` (object cache) and
//! `<source_hash>.relon-ir-v1` (legacy IR cache).
//!
//! Byte format (little-endian, version-prefixed for forward
//! compatibility):
//!
//! ```text
//! magic           : [u8; 4] = b"RLSC"
//! format_version  : u32     = 2
//! body_len        : u32     // body bytes that follow
//! body            : [u8; N] // bincode-encoded SchemaCacheEntry
//! hmac_tag        : [u8; 32]// HMAC-SHA256 over
//!                           //   bind_prefix || bytes[0 .. body end]
//!                           // where `bind_prefix` is
//!                           //   b"RLSC-v2"
//!                           //   || source_sha256          (32 B)
//!                           //   || object_sha256          (32 B)
//!                           //   || entry_shape_u8         (1 B)
//!                           //   || entry_arity_le32       (4 B)
//! ```
//!
//! v1 used a self-attesting SHA-256 trailer; an attacker who could
//! write the sidecar could just re-hash. v2 swaps the trailer to an
//! HMAC over the per-installation key + the prefix bytes above, so
//! the sidecar is bound to the object cache it ships beside. The
//! load path refuses any decode when the HMAC key is absent.

use serde::{Deserialize, Serialize};

use relon_eval_api::schema_canonical::Schema;
use relon_object_cache::compute_hmac;
use relon_parser::TokenRange;

use crate::error::CraneliftError;

/// Magic prefix that tags the file as a relon schema cache.
pub const SCHEMA_CACHE_MAGIC: [u8; 4] = *b"RLSC";

/// Format version. Bump on incompatible layout changes.
///
/// v2 replaces the v1 SHA-256 self-attestation tail with an HMAC tag
/// that binds the sidecar to its object cache (`object_sha256`),
/// source key (`source_sha256`), and entry shape + arity. v1 files
/// are rejected with a version-mismatch error so any stale sidecar
/// is regenerated by the next cold start.
pub const SCHEMA_CACHE_VERSION: u32 = 2;

/// Filename suffix for the schema cache. Keep aligned with the
/// object-cache + IR-cache naming so a host's GC sweep over either
/// catches all three.
pub const SCHEMA_CACHE_FILE_SUFFIX: &str = ".relon-schema-v1";

/// Side-table mirror of the bits a `from_cache_dir` constructor needs
/// to rebuild a `AotEvaluator` against a dlopen'd ET_DYN.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SchemaCacheEntry {
    /// Canonical schema of the `#main` arguments. The buffer-protocol
    /// trampoline writes user args into this layout before calling
    /// the dlopen'd `run_main`.
    pub main_schema: Schema,
    /// Canonical schema of the `#main` return record.
    pub return_schema: Schema,
    /// Parameter names in declaration order. Surfaced through
    /// `AotEvaluator::param_names()`.
    pub param_names: Vec<String>,
    /// Const-data bytes referenced by `Op::ConstString` /
    /// `Op::ConstList*` in the cached object. The trampoline copies
    /// these into the arena prefix before each invocation; the
    /// dlopen'd code dereferences fixed `iconst(I32, offset)` values
    /// against them.
    pub const_data: Vec<u8>,
    /// Number of `__closure_<N>` symbols the loader must `dlsym` from
    /// the ET_DYN. Pairs with the codegen's `closure_table` length.
    pub closure_count: u32,
    /// Entry shape detected at codegen time. Determines whether the
    /// trampoline uses the legacy `(I64...) -> I64` path or the
    /// buffer-protocol `(I32×4, I64) -> I32` path.
    pub entry_shape: SerEntryShape,
    /// Entry arity (number of IR-declared `#main` params; doesn't
    /// count the implicit sandbox-state pointer).
    pub entry_arity: u32,
    /// Source range of the lowered `#main` directive. Carried so the
    /// trampoline can attach diagnostics to traps emitted by the
    /// dlopen'd code.
    pub entry_range: SerTokenRange,
}

/// Serializable mirror of `crate::codegen::EntryShape`. Kept in
/// sync with the codegen-side enum; an incompatible variant change
/// is gated by [`SCHEMA_CACHE_VERSION`].
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum SerEntryShape {
    LegacyI64Args = 0,
    BufferProtocol = 1,
}

/// Serializable mirror of [`relon_parser::TokenRange`]. We embed the
/// raw (line, column, offset) pairs so a host that does not depend
/// on `relon-parser`'s internal types can still decode.
#[derive(Debug, Clone, Copy, Default, Serialize, Deserialize)]
pub struct SerTokenRange {
    pub start_line: u32,
    pub start_column: u64,
    pub start_offset: u64,
    pub end_line: u32,
    pub end_column: u64,
    pub end_offset: u64,
}

impl From<TokenRange> for SerTokenRange {
    fn from(r: TokenRange) -> Self {
        Self {
            start_line: r.start.line,
            start_column: r.start.column as u64,
            start_offset: r.start.offset as u64,
            end_line: r.end.line,
            end_column: r.end.column as u64,
            end_offset: r.end.offset as u64,
        }
    }
}

impl From<SerTokenRange> for TokenRange {
    fn from(s: SerTokenRange) -> Self {
        Self {
            start: relon_parser::TokenPosition {
                line: s.start_line,
                column: s.start_column as usize,
                offset: s.start_offset as usize,
            },
            end: relon_parser::TokenPosition {
                line: s.end_line,
                column: s.end_column as usize,
                offset: s.end_offset as usize,
            },
        }
    }
}

/// Domain-separation prefix for the HMAC computation. Keeps the
/// schema-cache HMAC distinct from the relon-object-cache HMAC even
/// if a future refactor shares the same per-installation key.
const SCHEMA_CACHE_HMAC_DOMAIN: &[u8] = b"RLSC-v2";

/// Build the bytes that the HMAC tag is computed over. The HMAC
/// covers a binding prefix (domain tag + source/object hashes +
/// entry shape + arity) followed by the entire serialized body
/// (header + bincode payload). An attacker who flips even one bit
/// in any of those bindings produces a HMAC mismatch.
fn hmac_input(
    body_with_header: &[u8],
    source_sha256: &[u8; 32],
    object_sha256: &[u8; 32],
    entry_shape: SerEntryShape,
    entry_arity: u32,
) -> Vec<u8> {
    let mut input = Vec::with_capacity(
        SCHEMA_CACHE_HMAC_DOMAIN.len() + 32 + 32 + 1 + 4 + body_with_header.len(),
    );
    input.extend_from_slice(SCHEMA_CACHE_HMAC_DOMAIN);
    input.extend_from_slice(source_sha256);
    input.extend_from_slice(object_sha256);
    input.push(entry_shape as u8);
    input.extend_from_slice(&entry_arity.to_le_bytes());
    input.extend_from_slice(body_with_header);
    input
}

/// Encode a [`SchemaCacheEntry`] into the on-disk byte form. The
/// trailing HMAC tag is computed against the per-installation key
/// passed in `hmac_key` and binds the encoded body to the object
/// cache it ships beside (`object_sha256`) plus the source-key the
/// filename stem is derived from (`source_sha256`). Callers without
/// a key must refuse to write the sidecar at all — the integration
/// layer enforces this above us.
///
/// Uses serde_json for the body because `relon_eval_api::schema_canonical::TypeRepr`
/// is tagged with `#[serde(tag = "kind")]` (internally tagged), which
/// bincode 1.x's lack of `deserialize_any` rejects. JSON keeps the
/// dependency surface narrow and the decode hot path stays under
/// 10 µs for typical entries (< 1 KB).
pub fn serialize(
    entry: &SchemaCacheEntry,
    source_sha256: &[u8; 32],
    object_sha256: &[u8; 32],
    hmac_key: &[u8; 32],
) -> Result<Vec<u8>, CraneliftError> {
    let body = serde_json::to_vec(entry)
        .map_err(|e| CraneliftError::Cache(format!("schema cache encode: {e}")))?;
    let body_len = u32::try_from(body.len())
        .map_err(|_| CraneliftError::Cache("schema cache body too large for u32".into()))?;
    let mut out = Vec::with_capacity(body.len() + 16 + 32);
    out.extend_from_slice(&SCHEMA_CACHE_MAGIC);
    out.extend_from_slice(&SCHEMA_CACHE_VERSION.to_le_bytes());
    out.extend_from_slice(&body_len.to_le_bytes());
    out.extend_from_slice(&body);
    let mac_input = hmac_input(
        &out,
        source_sha256,
        object_sha256,
        entry.entry_shape,
        entry.entry_arity,
    );
    let tag = compute_hmac(&mac_input, hmac_key);
    out.extend_from_slice(&tag);
    Ok(out)
}

/// Decode the on-disk byte form back into a [`SchemaCacheEntry`].
///
/// Verifies the trailing HMAC tag against the same `source_sha256` +
/// `object_sha256` + entry-shape + arity bindings the writer used.
/// A tampered body, swapped object cache, or mismatched source key
/// each surface as a hmac-mismatch error so the caller can invalidate
/// the cache triple fail-closed.
pub fn deserialize(
    bytes: &[u8],
    source_sha256: &[u8; 32],
    object_sha256: &[u8; 32],
    hmac_key: &[u8; 32],
) -> Result<SchemaCacheEntry, CraneliftError> {
    if bytes.len() < 4 + 4 + 4 + 32 {
        return Err(CraneliftError::Cache("schema cache too short".into()));
    }
    if bytes[..4] != SCHEMA_CACHE_MAGIC {
        return Err(CraneliftError::Cache("schema cache magic mismatch".into()));
    }
    let version = u32::from_le_bytes(bytes[4..8].try_into().unwrap());
    if version != SCHEMA_CACHE_VERSION {
        return Err(CraneliftError::Cache(format!(
            "schema cache version mismatch: expected {SCHEMA_CACHE_VERSION}, got {version}"
        )));
    }
    let body_len = u32::from_le_bytes(bytes[8..12].try_into().unwrap()) as usize;
    let body_end = 12 + body_len;
    if bytes.len() < body_end + 32 {
        return Err(CraneliftError::Cache("schema cache truncated".into()));
    }
    let stored_tag = &bytes[body_end..body_end + 32];
    // Decode the entry first so we can fold its entry-shape + arity
    // into the HMAC binding. A failed decode bails before we expose
    // any unverified bytes to the loader.
    let entry: SchemaCacheEntry = serde_json::from_slice(&bytes[12..body_end])
        .map_err(|e| CraneliftError::Cache(format!("schema cache decode: {e}")))?;
    let mac_input = hmac_input(
        &bytes[..body_end],
        source_sha256,
        object_sha256,
        entry.entry_shape,
        entry.entry_arity,
    );
    let expected = compute_hmac(&mac_input, hmac_key);
    // Constant-time compare via the underlying `verify_slice` path.
    if !relon_object_cache::verify_hmac(
        &mac_input,
        hmac_key,
        stored_tag
            .try_into()
            .map_err(|_| CraneliftError::Cache("schema cache hmac tag size".into()))?,
    ) {
        // Drop `expected` purely to discourage debug-print leakage of
        // the just-computed tag in error messages.
        let _ = expected;
        return Err(CraneliftError::Cache("schema cache hmac mismatch".into()));
    }
    Ok(entry)
}

/// Build the canonical schema-cache path next to the object-cache
/// blob. Matching filename stem lets a host's GC catch the pair.
pub fn schema_cache_path_for(
    cache_dir: &std::path::Path,
    source_sha256: [u8; 32],
) -> std::path::PathBuf {
    let mut name = String::with_capacity(64 + SCHEMA_CACHE_FILE_SUFFIX.len());
    for b in source_sha256.iter() {
        use std::fmt::Write as _;
        let _ = write!(&mut name, "{:02x}", b);
    }
    name.push_str(SCHEMA_CACHE_FILE_SUFFIX);
    cache_dir.join(name)
}

#[cfg(test)]
mod tests {
    use super::*;
    use relon_eval_api::schema_canonical::{Field, TypeRepr};

    fn sample_entry() -> SchemaCacheEntry {
        let main = Schema {
            is_tuple: false,
            name: "MainArgs".into(),
            generics: Vec::new(),
            fields: vec![Field {
                name: "x".into(),
                ty: TypeRepr::Int,
                default: None,
            }],
        };
        let ret = Schema {
            is_tuple: false,
            name: "MainReturn".into(),
            generics: Vec::new(),
            fields: vec![Field {
                name: "value".into(),
                ty: TypeRepr::Int,
                default: None,
            }],
        };
        SchemaCacheEntry {
            main_schema: main,
            return_schema: ret,
            param_names: vec!["x".into()],
            const_data: vec![],
            closure_count: 0,
            entry_shape: SerEntryShape::BufferProtocol,
            entry_arity: 1,
            entry_range: SerTokenRange::default(),
        }
    }

    fn fixture_keys() -> ([u8; 32], [u8; 32], [u8; 32]) {
        let mut src = [0u8; 32];
        let mut obj = [0u8; 32];
        let mut key = [0u8; 32];
        for i in 0..32 {
            src[i] = 0x11u8.wrapping_add(i as u8);
            obj[i] = 0x22u8.wrapping_add(i as u8);
            key[i] = 0x33u8.wrapping_add(i as u8);
        }
        (src, obj, key)
    }

    #[test]
    fn schema_cache_round_trip() {
        let entry = sample_entry();
        let (src, obj, key) = fixture_keys();
        let bytes = serialize(&entry, &src, &obj, &key).expect("serialize");
        let back = deserialize(&bytes, &src, &obj, &key).expect("deserialize");
        assert_eq!(back.main_schema.name, entry.main_schema.name);
        assert_eq!(back.return_schema.name, entry.return_schema.name);
        assert_eq!(back.entry_arity, entry.entry_arity);
        assert_eq!(back.entry_shape as u8, entry.entry_shape as u8);
    }

    #[test]
    fn schema_cache_rejects_magic_corruption() {
        let (src, obj, key) = fixture_keys();
        let mut bytes = serialize(&sample_entry(), &src, &obj, &key).unwrap();
        bytes[0] = b'X';
        let err = deserialize(&bytes, &src, &obj, &key).expect_err("magic check");
        assert!(format!("{err}").contains("magic"));
    }

    #[test]
    fn schema_cache_rejects_tag_corruption() {
        let (src, obj, key) = fixture_keys();
        let mut bytes = serialize(&sample_entry(), &src, &obj, &key).unwrap();
        let last = bytes.len() - 1;
        bytes[last] ^= 0xff;
        let err = deserialize(&bytes, &src, &obj, &key).expect_err("hmac");
        assert!(format!("{err}").contains("hmac"));
    }

    #[test]
    fn schema_cache_rejects_mismatched_object_hash() {
        // Attacker can flip the sidecar; the HMAC must reject when
        // the loader supplies a different `object_sha256` (i.e. the
        // sidecar is paired with a swapped ET_DYN).
        let (src, obj, key) = fixture_keys();
        let bytes = serialize(&sample_entry(), &src, &obj, &key).unwrap();
        let mut swapped = obj;
        swapped[0] ^= 0xff;
        let err = deserialize(&bytes, &src, &swapped, &key).expect_err("hmac");
        assert!(format!("{err}").contains("hmac"));
    }

    #[test]
    fn schema_cache_rejects_mismatched_source_hash() {
        let (src, obj, key) = fixture_keys();
        let bytes = serialize(&sample_entry(), &src, &obj, &key).unwrap();
        let mut other_src = src;
        other_src[31] ^= 0x01;
        let err = deserialize(&bytes, &other_src, &obj, &key).expect_err("hmac");
        assert!(format!("{err}").contains("hmac"));
    }

    #[test]
    fn schema_cache_rejects_v1_layout() {
        // v1 sidecars (sha256-only) must not be accepted by v2 readers
        // — the version mismatch forces a regen on the next cold start
        // so the HMAC binding is in place before the next dlopen call.
        let (src, obj, key) = fixture_keys();
        let mut bytes = serialize(&sample_entry(), &src, &obj, &key).unwrap();
        // Patch the version field back to 1.
        bytes[4..8].copy_from_slice(&1u32.to_le_bytes());
        let err = deserialize(&bytes, &src, &obj, &key).expect_err("version");
        assert!(format!("{err}").contains("version mismatch"));
    }
}
