import 'dart:nativewrappers/_internal/vm/lib/typed_data_patch.dart';

import 'package:flutter/cupertino.dart';
import 'package:pictorial_core/pictorial_core.dart';

import '../pom/entity.dart';
import 'entities.dart';

class PersonPrototype {
  late String name;
  late String? textDescription;
  late String? negativeTextDescription;
  late String? loraId;
  late List<(String, Uint8List)>? referenceImages;

  PersonPrototype(this.name, {this.textDescription, this.negativeTextDescription, this.loraId, this.referenceImages});

  PersonPrototype.from(Map<String, dynamic> bson) {
    this.name = bson['name'];
    this.textDescription = bson['textDescription'];
    this.negativeTextDescription = bson['negativeTextDescription'];
    this.loraId = bson['loraId'];
    this.referenceImages = bson['referenceImages'];
  }

  Map<String, dynamic> dump() {
    var referenceImages = this
        .referenceImages
        ?.map((e) => {
              'description': e.$1,
              'image': e.$2,
            })
        .toList();

    return {
      'name': name,
      'textDescription': textDescription,
      'negativeTextDescription': negativeTextDescription,
      'loraId': loraId,
      'referenceImages': referenceImages,
    };
  }

  void newReferenceImage(String description, Uint8List image) {
    if (referenceImages == null) {
      referenceImages = [];
    }
    referenceImages!.add((description, image));
  }
}

class Person implements Entity {
  PersonPrototype? _prototype;

  late String _name;
  late String? _textDescription;
  late String? _negativeTextDescription;
  late Uint8List? _referenceImage;
  late Map<String, dynamic>? _pose; // including face, body, and hand pose..

  @override
  String id;

  Person(this.id);

  Person.fromPrototype(this.id, this._prototype) {
    _name = _prototype!.name;
    _textDescription = _prototype!.textDescription;
    _negativeTextDescription = _prototype!.negativeTextDescription;
    _referenceImage = _prototype!.referenceImages?.first.$2;
  }

  Person.fromBson(this.id, Map<String, dynamic> bson) {
    this.id = bson['_id'];
    this.decode(bson);
  }

  // getters, setters
  String get textDescription => _textDescription!;

  String get negativeTextDescription => _negativeTextDescription!;

  Uint8List get referenceImage => _referenceImage!;

  Map<String, dynamic> get pose => _pose!;

  set textDescription(String textDescription) => _textDescription = textDescription;

  set negativeTextDescription(String negativeTextDescription) => _negativeTextDescription = negativeTextDescription;

  set referenceImage(Uint8List referenceImage) => _referenceImage = referenceImage;

  set pose(Map<String, dynamic> pose) => _pose = pose;

  @override
  decode(Map<String, dynamic> bson) {
    _name = bson['name'];
    _textDescription = bson['textDescription'];
    _negativeTextDescription = bson['negativeTextDescription'];
    _referenceImage = bson['referenceImage'];
    _pose = bson['pose'];
  }

  @override
  Map<String, dynamic> encode() {
    return {
      'name': _name,
      'textDescription': _textDescription,
      'negativeTextDescription': _negativeTextDescription,
      'referenceImage': _referenceImage,
      'pose': _pose,
    };
  }

  @override
  void from(Entity entity) {
    switch (entity.runtimeType) {
      case Unspecified u:
        warn('Additional information may be needed when transforming Unspecified to Person');
        _textDescription = u.textDescription;
        _referenceImage = u.image as Uint8List?;
        break;
      case Scene s:
        warn('Additional information may be needed when transforming Scene to Person');
        _textDescription = s.textDescription;
        _referenceImage = s.image as Uint8List?;
        break;

      case Person _:
      case Shape _:
      case Txt _:
      default:
        throw Exception('Cannot transform to Person from ${entity.runtimeType}');
    }
  }

  @override
  IconData get icon => CupertinoIcons.person_2;

  @override
  Widget render({editable = false}) {
    // TODO: implement render
    throw UnimplementedError();
    // Case1: A Person Common Placeholder
    // Case2: A Person with PoseData Placeholder
    // Case3: A Pure(without background) Person photo that generated by AI
  }
}
