//! Coverage ledger for the lowering capability-cap sites.
//!
//! Every loud "unsupported" cap in the lowering pass (each [`cap!`] site,
//! see `relon_ir::lowering::cap::LOWERING_CAP_IDS`) has exactly one
//! [`LedgerEntry`] here. The ledger is the human-auditable companion to
//! the machine registry: it records, per cap id, which family the
//! construct belongs to, whether it is already covered by the real
//! four-way differential or still capped, and an honest one-line reason.
//!
//! The `ledger_completeness` integration test enforces a bijection
//! between [`LEDGER`] and `LOWERING_CAP_IDS` — no orphan ledger row, no
//! unregistered cap — so a future cap added without a ledger entry fails
//! the build. As constructs gain real coverage in later value-model
//! waves, their entries flip from [`Status::Capped`] to
//! [`Status::Covered`] and gain a `corpus` probe name.

/// One row per lowering cap id.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct LedgerEntry {
    /// Stable cap id, matching an entry in
    /// `relon_ir::lowering::cap::LOWERING_CAP_IDS`.
    pub id: &'static str,
    /// Human-readable source location (`file::fn`) for quick navigation.
    /// Deliberately line-number-free so edits above the site don't churn
    /// the ledger.
    pub site: &'static str,
    /// Construct family the cap belongs to.
    pub category: Category,
    /// Whether the construct is already covered by the real four-way
    /// differential today, or still capped.
    pub status: Status,
    /// CorpusCase / probe name that exercises this id, or `""` if none yet.
    pub corpus: &'static str,
    /// Honest one-line reason the construct is capped (or how it is
    /// covered, once flipped).
    pub reason: &'static str,
}

/// Coverage state of a cap id.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Status {
    /// The construct passes the real four-way differential today.
    Covered,
    /// The construct is rejected with a loud cap; not yet lowerable.
    Capped,
}

/// Construct family a cap belongs to. Mirrors the rough `LoweringError`
/// variant grouping used by the coverage worklist.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Category {
    /// Expression-shape caps (`UnsupportedExpr`, unresolved variables,
    /// stdlib resolution, ternary typing).
    ExprShape,
    /// `#main` signature parameter / return type caps.
    MainSignatureType,
    /// Schema / dict field type caps.
    FieldType,
    /// Operator caps.
    Operator,
    /// Closure-boundary / closure-capture caps.
    Closure,
    /// Cross-module schema merge / brand / default-dependency caps.
    SchemaMerge,
    /// Host-infrastructure caps (missing / duplicate / absent entry).
    HostInfra,
}

/// One entry per lowering cap id. See module docs for the bijection
/// invariant the completeness test enforces.
pub const LEDGER: &[LedgerEntry] = &[
    LedgerEntry {
        id: "lower_workspace.entry_module_not_found.1",
        site: "lowering/mod.rs::lower_workspace",
        category: Category::HostInfra,
        status: Status::Capped,
        corpus: "",
        reason: "host gave an entry id absent from the workspace; not a lowerable construct",
    },
    LedgerEntry {
        id: "lower_workspace.entry_module_not_found.2",
        site: "lowering/mod.rs::lower_workspace",
        category: Category::HostInfra,
        status: Status::Capped,
        corpus: "",
        reason: "host gave an entry id absent from the workspace; not a lowerable construct",
    },
    LedgerEntry {
        id: "lower_workspace.multiple_main_directives",
        site: "lowering/mod.rs::lower_workspace",
        category: Category::HostInfra,
        status: Status::Capped,
        corpus: "",
        reason: "more than one reachable module declares #main; ambiguous entry",
    },
    LedgerEntry {
        id: "detect_cross_file_schema_conflicts.duplicate_schema_across_files",
        site: "lowering/mod.rs::detect_cross_file_schema_conflicts",
        category: Category::SchemaMerge,
        status: Status::Capped,
        corpus: "",
        reason: "same schema name with divergent shapes across modules; no canonical merge",
    },
    LedgerEntry {
        id: "lower_entry_with_resolver.missing_main",
        site: "lowering/mod.rs::lower_entry_with_resolver",
        category: Category::HostInfra,
        status: Status::Capped,
        corpus: "",
        reason: "module has no #main; library/config files are not entry programs",
    },
    LedgerEntry {
        id: "lower_entry_with_resolver.closure_across_boundary.1",
        site: "lowering/mod.rs::lower_entry_with_resolver",
        category: Category::Closure,
        status: Status::Capped,
        corpus: "",
        reason: "closure value would dangle if it crossed the wasm module boundary",
    },
    LedgerEntry {
        id: "lower_entry_with_resolver.closure_across_boundary.2",
        site: "lowering/mod.rs::lower_entry_with_resolver",
        category: Category::Closure,
        status: Status::Capped,
        corpus: "",
        reason: "closure value would dangle if it crossed the wasm module boundary",
    },
    LedgerEntry {
        id: "lower_entry_with_resolver.unsupported_expr.1",
        site: "lowering/mod.rs::lower_entry_with_resolver",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "lower_entry_with_resolver.unsupported_expr.2",
        site: "lowering/mod.rs::lower_entry_with_resolver",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "lower_entry_with_resolver.unsupported_type_in_main",
        site: "lowering/mod.rs::lower_entry_with_resolver",
        category: Category::MainSignatureType,
        status: Status::Capped,
        corpus: "",
        reason: "#main param/return type outside the buffer-protocol decode envelope",
    },
    LedgerEntry {
        id: "lower_entry_with_resolver.unsupported_expr.3",
        site: "lowering/mod.rs::lower_entry_with_resolver",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "build_main_params_schema.unsupported_type_in_main",
        site: "lowering/mod.rs::build_main_params_schema",
        category: Category::MainSignatureType,
        status: Status::Capped,
        corpus: "",
        reason: "#main param/return type outside the buffer-protocol decode envelope",
    },
    LedgerEntry {
        id: "build_main_return_schema.unsupported_type_in_main.1",
        site: "lowering/mod.rs::build_main_return_schema",
        category: Category::MainSignatureType,
        status: Status::Capped,
        corpus: "",
        reason: "#main param/return type outside the buffer-protocol decode envelope",
    },
    LedgerEntry {
        id: "build_main_return_schema.unsupported_type_in_main.2",
        site: "lowering/mod.rs::build_main_return_schema",
        category: Category::MainSignatureType,
        status: Status::Capped,
        corpus: "",
        reason: "#main param/return type outside the buffer-protocol decode envelope",
    },
    LedgerEntry {
        id: "anon_dict_return_plan.unsupported_expr",
        site: "lowering/mod.rs::anon_dict_return_plan",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "anon_dict_return_plan.closure_across_boundary",
        site: "lowering/mod.rs::anon_dict_return_plan",
        category: Category::Closure,
        status: Status::Capped,
        corpus: "",
        reason: "closure value would dangle if it crossed the wasm module boundary",
    },
    LedgerEntry {
        id: "anon_dict_return_plan.unsupported_field_type",
        site: "lowering/mod.rs::anon_dict_return_plan",
        category: Category::FieldType,
        status: Status::Capped,
        corpus: "",
        reason: "schema/dict field type has no canonical layout in this position",
    },
    LedgerEntry {
        id: "classify_anon_dict_scalar_field.unsupported_expr",
        site: "lowering/mod.rs::classify_anon_dict_scalar_field",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "classify_anon_dict_str_int_field.unsupported_expr.1",
        site: "lowering/mod.rs::classify_anon_dict_str_int_field",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "classify_anon_dict_str_int_field.unsupported_expr.2",
        site: "lowering/mod.rs::classify_anon_dict_str_int_field",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "classify_anon_dict_list_string_field.unsupported_expr",
        site: "lowering/mod.rs::classify_anon_dict_list_string_field",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "classify_anon_dict_list_field.unsupported_field_type.1",
        site: "lowering/mod.rs::classify_anon_dict_list_field",
        category: Category::FieldType,
        status: Status::Capped,
        corpus: "",
        reason: "schema/dict field type has no canonical layout in this position",
    },
    LedgerEntry {
        id: "classify_anon_dict_list_field.unsupported_field_type.2",
        site: "lowering/mod.rs::classify_anon_dict_list_field",
        category: Category::FieldType,
        status: Status::Capped,
        corpus: "",
        reason: "schema/dict field type has no canonical layout in this position",
    },
    LedgerEntry {
        id: "classify_anon_dict_list_field.unsupported_field_type.3",
        site: "lowering/mod.rs::classify_anon_dict_list_field",
        category: Category::FieldType,
        status: Status::Capped,
        corpus: "",
        reason: "schema/dict field type has no canonical layout in this position",
    },
    LedgerEntry {
        id: "classify_anon_dict_scalar_field_irt.unsupported_expr.1",
        site: "lowering/mod.rs::classify_anon_dict_scalar_field_irt",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "classify_anon_dict_scalar_field_irt.unsupported_expr.2",
        site: "lowering/mod.rs::classify_anon_dict_scalar_field_irt",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "classify_anon_dict_scalar_field_irt.unsupported_expr.3",
        site: "lowering/mod.rs::classify_anon_dict_scalar_field_irt",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "classify_anon_dict_scalar_field_irt.unsupported_expr.4",
        site: "lowering/mod.rs::classify_anon_dict_scalar_field_irt",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "lower_anon_dict_body.unsupported_expr.1",
        site: "lowering/mod.rs::lower_anon_dict_body",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "lower_anon_dict_body.unsupported_expr.2",
        site: "lowering/mod.rs::lower_anon_dict_body",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "lower_anon_dict_body.unsupported_expr.3",
        site: "lowering/mod.rs::lower_anon_dict_body",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "lower_anon_dict_body.unsupported_field_type.1",
        site: "lowering/mod.rs::lower_anon_dict_body",
        category: Category::FieldType,
        status: Status::Capped,
        corpus: "",
        reason: "schema/dict field type has no canonical layout in this position",
    },
    LedgerEntry {
        id: "lower_anon_dict_body.unsupported_expr.4",
        site: "lowering/mod.rs::lower_anon_dict_body",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "lower_anon_dict_body.unsupported_field_type.2",
        site: "lowering/mod.rs::lower_anon_dict_body",
        category: Category::FieldType,
        status: Status::Capped,
        corpus: "",
        reason: "schema/dict field type has no canonical layout in this position",
    },
    LedgerEntry {
        id: "lower_anon_dict_body.unsupported_expr.5",
        site: "lowering/mod.rs::lower_anon_dict_body",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "lower_anon_dict_body.unsupported_expr.6",
        site: "lowering/mod.rs::lower_anon_dict_body",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "lower_anon_dict_body.unsupported_expr.7",
        site: "lowering/mod.rs::lower_anon_dict_body",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "lower_anon_dict_body.unsupported_field_type.3",
        site: "lowering/mod.rs::lower_anon_dict_body",
        category: Category::FieldType,
        status: Status::Capped,
        corpus: "",
        reason: "schema/dict field type has no canonical layout in this position",
    },
    LedgerEntry {
        id: "lower_anon_dict_body.unsupported_expr.8",
        site: "lowering/mod.rs::lower_anon_dict_body",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "type_repr_to_ir_type.unsupported_type_in_main.1",
        site: "lowering/mod.rs::type_repr_to_ir_type",
        category: Category::MainSignatureType,
        status: Status::Capped,
        corpus: "",
        reason: "#main param/return type outside the buffer-protocol decode envelope",
    },
    LedgerEntry {
        id: "type_repr_to_ir_type.unsupported_type_in_main.2",
        site: "lowering/mod.rs::type_repr_to_ir_type",
        category: Category::MainSignatureType,
        status: Status::Capped,
        corpus: "",
        reason: "#main param/return type outside the buffer-protocol decode envelope",
    },
    LedgerEntry {
        id: "lower_expr.unsupported_expr.1",
        site: "lowering/mod.rs::lower_expr",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "lower_expr.unsupported_expr.2",
        site: "lowering/mod.rs::lower_expr",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "lower_expr.unsupported_expr.3",
        site: "lowering/mod.rs::lower_expr",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "lower_expr.unsupported_expr.4",
        site: "lowering/mod.rs::lower_expr",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "lower_expr.unsupported_expr.5",
        site: "lowering/mod.rs::lower_expr",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "lower_expr.unsupported_expr.6",
        site: "lowering/mod.rs::lower_expr",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "lower_expr.unsupported_expr.7",
        site: "lowering/mod.rs::lower_expr",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "lower_expr.closure_across_boundary",
        site: "lowering/mod.rs::lower_expr",
        category: Category::Closure,
        status: Status::Capped,
        corpus: "",
        reason: "closure value would dangle if it crossed the wasm module boundary",
    },
    LedgerEntry {
        id: "lower_expr.unsupported_expr.8",
        site: "lowering/mod.rs::lower_expr",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "try_lower_local_closure_call.unsupported_expr.1",
        site: "lowering/mod.rs::try_lower_local_closure_call",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "try_lower_local_closure_call.unknown_stdlib_method",
        site: "lowering/mod.rs::try_lower_local_closure_call",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "method/function name + arity matches no stdlib signature",
    },
    LedgerEntry {
        id: "try_lower_local_closure_call.unsupported_expr.2",
        site: "lowering/mod.rs::try_lower_local_closure_call",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "try_lower_local_closure_call.unsupported_expr.3",
        site: "lowering/mod.rs::try_lower_local_closure_call",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "try_lower_local_closure_call.stdlib_arg_type_mismatch",
        site: "lowering/mod.rs::try_lower_local_closure_call",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "stdlib call argument type disagrees with the declared signature",
    },
    LedgerEntry {
        id: "try_lower_native_call.unsupported_expr.1",
        site: "lowering/mod.rs::try_lower_native_call",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "try_lower_native_call.unsupported_expr.2",
        site: "lowering/mod.rs::try_lower_native_call",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "try_lower_native_call.unsupported_expr.3",
        site: "lowering/mod.rs::try_lower_native_call",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "lower_fn_call.unsupported_expr.1",
        site: "lowering/mod.rs::lower_fn_call",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "lower_fn_call.unsupported_expr.2",
        site: "lowering/mod.rs::lower_fn_call",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "lower_fn_call.unknown_stdlib_method.1",
        site: "lowering/mod.rs::lower_fn_call",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "method/function name + arity matches no stdlib signature",
    },
    LedgerEntry {
        id: "lower_fn_call.unknown_stdlib_method.2",
        site: "lowering/mod.rs::lower_fn_call",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "method/function name + arity matches no stdlib signature",
    },
    LedgerEntry {
        id: "lower_fn_call.unknown_stdlib_method.3",
        site: "lowering/mod.rs::lower_fn_call",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "method/function name + arity matches no stdlib signature",
    },
    LedgerEntry {
        id: "lower_fn_call.unsupported_expr.3",
        site: "lowering/mod.rs::lower_fn_call",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "lower_fn_call.unsupported_expr.4",
        site: "lowering/mod.rs::lower_fn_call",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "lower_fn_call.unknown_stdlib_method.4",
        site: "lowering/mod.rs::lower_fn_call",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "method/function name + arity matches no stdlib signature",
    },
    LedgerEntry {
        id: "lower_fn_call.unknown_stdlib_method.5",
        site: "lowering/mod.rs::lower_fn_call",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "method/function name + arity matches no stdlib signature",
    },
    LedgerEntry {
        id: "lower_fn_call.unknown_stdlib_method.6",
        site: "lowering/mod.rs::lower_fn_call",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "method/function name + arity matches no stdlib signature",
    },
    LedgerEntry {
        id: "lower_fn_call.unsupported_expr.5",
        site: "lowering/mod.rs::lower_fn_call",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "lower_fn_call.unsupported_expr.6",
        site: "lowering/mod.rs::lower_fn_call",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "lower_list_index_typed.unsupported_expr",
        site: "lowering/mod.rs::lower_list_index_typed",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "lower_list_string_index.unsupported_expr",
        site: "lowering/mod.rs::lower_list_string_index",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "lower_dict_string_index.unsupported_expr.1",
        site: "lowering/mod.rs::lower_dict_string_index",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "lower_dict_string_index.unsupported_expr.2",
        site: "lowering/mod.rs::lower_dict_string_index",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "lower_dict_string_index.unsupported_expr.3",
        site: "lowering/mod.rs::lower_dict_string_index",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "expect_int_top.unsupported_expr.1",
        site: "lowering/mod.rs::expect_int_top",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "expect_int_top.unsupported_expr.2",
        site: "lowering/mod.rs::expect_int_top",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "lower_stdlib_arg.unknown_stdlib_method",
        site: "lowering/mod.rs::lower_stdlib_arg",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "method/function name + arity matches no stdlib signature",
    },
    LedgerEntry {
        id: "lower_stdlib_arg.unsupported_expr.1",
        site: "lowering/mod.rs::lower_stdlib_arg",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "lower_stdlib_arg.unsupported_expr.2",
        site: "lowering/mod.rs::lower_stdlib_arg",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "lower_stdlib_arg.unsupported_expr.3",
        site: "lowering/mod.rs::lower_stdlib_arg",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "lower_method_receiver.unsupported_expr.1",
        site: "lowering/mod.rs::lower_method_receiver",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "lower_method_receiver.unsupported_expr.2",
        site: "lowering/mod.rs::lower_method_receiver",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "finish_schema_method_call.unknown_stdlib_method",
        site: "lowering/mod.rs::finish_schema_method_call",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "method/function name + arity matches no stdlib signature",
    },
    LedgerEntry {
        id: "finish_schema_method_call.unsupported_expr.1",
        site: "lowering/mod.rs::finish_schema_method_call",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "finish_schema_method_call.stdlib_arg_type_mismatch.1",
        site: "lowering/mod.rs::finish_schema_method_call",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "stdlib call argument type disagrees with the declared signature",
    },
    LedgerEntry {
        id: "finish_schema_method_call.unsupported_expr.2",
        site: "lowering/mod.rs::finish_schema_method_call",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "finish_schema_method_call.unsupported_expr.3",
        site: "lowering/mod.rs::finish_schema_method_call",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "finish_schema_method_call.stdlib_arg_type_mismatch.2",
        site: "lowering/mod.rs::finish_schema_method_call",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "stdlib call argument type disagrees with the declared signature",
    },
    LedgerEntry {
        id: "check_stdlib_arg.unknown_stdlib_method",
        site: "lowering/mod.rs::check_stdlib_arg",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "method/function name + arity matches no stdlib signature",
    },
    LedgerEntry {
        id: "check_stdlib_arg.stdlib_arg_type_mismatch",
        site: "lowering/mod.rs::check_stdlib_arg",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "stdlib call argument type disagrees with the declared signature",
    },
    LedgerEntry {
        id: "lower_where.unsupported_expr.1",
        site: "lowering/mod.rs::lower_where",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "lower_where.unsupported_expr.2",
        site: "lowering/mod.rs::lower_where",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "lower_where.unsupported_expr.3",
        site: "lowering/mod.rs::lower_where",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "lower_where.unsupported_expr.4",
        site: "lowering/mod.rs::lower_where",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "lower_where.unsupported_expr.5",
        site: "lowering/mod.rs::lower_where",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "lower_where.unsupported_expr.6",
        site: "lowering/mod.rs::lower_where",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "lower_binary.unsupported_operator.1",
        site: "lowering/mod.rs::lower_binary",
        category: Category::Operator,
        status: Status::Capped,
        corpus: "",
        reason: "operator has no IR Op lowering on these operand types",
    },
    LedgerEntry {
        id: "lower_binary.unsupported_operator.2",
        site: "lowering/mod.rs::lower_binary",
        category: Category::Operator,
        status: Status::Capped,
        corpus: "",
        reason: "operator has no IR Op lowering on these operand types",
    },
    LedgerEntry {
        id: "lower_binary.unsupported_operator.3",
        site: "lowering/mod.rs::lower_binary",
        category: Category::Operator,
        status: Status::Capped,
        corpus: "",
        reason: "operator has no IR Op lowering on these operand types",
    },
    LedgerEntry {
        id: "lower_binary.unsupported_operator.4",
        site: "lowering/mod.rs::lower_binary",
        category: Category::Operator,
        status: Status::Capped,
        corpus: "",
        reason: "operator has no IR Op lowering on these operand types",
    },
    LedgerEntry {
        id: "lower_binary.unsupported_operator.5",
        site: "lowering/mod.rs::lower_binary",
        category: Category::Operator,
        status: Status::Capped,
        corpus: "",
        reason: "operator has no IR Op lowering on these operand types",
    },
    LedgerEntry {
        id: "lower_binary.unsupported_operator.6",
        site: "lowering/mod.rs::lower_binary",
        category: Category::Operator,
        status: Status::Capped,
        corpus: "",
        reason: "operator has no IR Op lowering on these operand types",
    },
    LedgerEntry {
        id: "lower_binary.unsupported_operator.7",
        site: "lowering/mod.rs::lower_binary",
        category: Category::Operator,
        status: Status::Capped,
        corpus: "",
        reason: "operator has no IR Op lowering on these operand types",
    },
    LedgerEntry {
        id: "lower_binary.unsupported_operator.8",
        site: "lowering/mod.rs::lower_binary",
        category: Category::Operator,
        status: Status::Capped,
        corpus: "",
        reason: "operator has no IR Op lowering on these operand types",
    },
    LedgerEntry {
        id: "lower_binary.unsupported_operator.9",
        site: "lowering/mod.rs::lower_binary",
        category: Category::Operator,
        status: Status::Capped,
        corpus: "",
        reason: "operator has no IR Op lowering on these operand types",
    },
    LedgerEntry {
        id: "lower_binary.unsupported_operator.10",
        site: "lowering/mod.rs::lower_binary",
        category: Category::Operator,
        status: Status::Capped,
        corpus: "",
        reason: "operator has no IR Op lowering on these operand types",
    },
    LedgerEntry {
        id: "lower_binary.unsupported_operator.11",
        site: "lowering/mod.rs::lower_binary",
        category: Category::Operator,
        status: Status::Capped,
        corpus: "",
        reason: "operator has no IR Op lowering on these operand types",
    },
    LedgerEntry {
        id: "lower_binary.unsupported_operator.12",
        site: "lowering/mod.rs::lower_binary",
        category: Category::Operator,
        status: Status::Capped,
        corpus: "",
        reason: "operator has no IR Op lowering on these operand types",
    },
    LedgerEntry {
        id: "lower_binary.unsupported_operator.13",
        site: "lowering/mod.rs::lower_binary",
        category: Category::Operator,
        status: Status::Capped,
        corpus: "",
        reason: "operator has no IR Op lowering on these operand types",
    },
    LedgerEntry {
        id: "lower_binary.unsupported_operator.14",
        site: "lowering/mod.rs::lower_binary",
        category: Category::Operator,
        status: Status::Capped,
        corpus: "",
        reason: "operator has no IR Op lowering on these operand types",
    },
    LedgerEntry {
        id: "lower_ternary.unsupported_expr",
        site: "lowering/mod.rs::lower_ternary",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "lower_ternary.if_condition_not_bool",
        site: "lowering/mod.rs::lower_ternary",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "ternary condition lowered to a non-Bool IR type",
    },
    LedgerEntry {
        id: "lower_ternary.if_branch_type_mismatch",
        site: "lowering/mod.rs::lower_ternary",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "ternary arms lowered to incompatible IR types",
    },
    LedgerEntry {
        id: "lower_branch.unsupported_expr",
        site: "lowering/mod.rs::lower_branch",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "canonical_schema_from_def.unsupported_expr",
        site: "lowering/mod.rs::canonical_schema_from_def",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "canonical_schema_from_def.cyclic_field_dependency",
        site: "lowering/mod.rs::canonical_schema_from_def",
        category: Category::SchemaMerge,
        status: Status::Capped,
        corpus: "",
        reason: "schema field defaults form a dependency cycle",
    },
    LedgerEntry {
        id: "canonical_schema_from_def.unsupported_field_type",
        site: "lowering/mod.rs::canonical_schema_from_def",
        category: Category::FieldType,
        status: Status::Capped,
        corpus: "",
        reason: "schema/dict field type has no canonical layout in this position",
    },
    LedgerEntry {
        id: "canonical_type_repr.unsupported_field_type.1",
        site: "lowering/mod.rs::canonical_type_repr",
        category: Category::FieldType,
        status: Status::Capped,
        corpus: "",
        reason: "schema/dict field type has no canonical layout in this position",
    },
    LedgerEntry {
        id: "canonical_type_repr.unsupported_field_type.2",
        site: "lowering/mod.rs::canonical_type_repr",
        category: Category::FieldType,
        status: Status::Capped,
        corpus: "",
        reason: "schema/dict field type has no canonical layout in this position",
    },
    LedgerEntry {
        id: "canonical_type_repr.unsupported_field_type.3",
        site: "lowering/mod.rs::canonical_type_repr",
        category: Category::FieldType,
        status: Status::Capped,
        corpus: "",
        reason: "schema/dict field type has no canonical layout in this position",
    },
    LedgerEntry {
        id: "topo_order_fields.missing_field_no_default",
        site: "lowering/mod.rs::topo_order_fields",
        category: Category::FieldType,
        status: Status::Capped,
        corpus: "",
        reason: "branded dict omits a field that has no schema-side default",
    },
    LedgerEntry {
        id: "topo_order_fields.cyclic_field_dependency",
        site: "lowering/mod.rs::topo_order_fields",
        category: Category::SchemaMerge,
        status: Status::Capped,
        corpus: "",
        reason: "schema field defaults form a dependency cycle",
    },
    LedgerEntry {
        id: "check_field_default_refs_resolvable.unknown_field_reference_in_default",
        site: "lowering/mod.rs::check_field_default_refs_resolvable",
        category: Category::SchemaMerge,
        status: Status::Capped,
        corpus: "",
        reason: "a field default references a non-existent sibling field",
    },
    LedgerEntry {
        id: "lower_dict_into_record.unknown_schema_brand",
        site: "lowering/mod.rs::lower_dict_into_record",
        category: Category::SchemaMerge,
        status: Status::Capped,
        corpus: "",
        reason: "dict literal names a schema brand not present in the analyzed tree",
    },
    LedgerEntry {
        id: "lower_dict_into_record.unsupported_expr.1",
        site: "lowering/mod.rs::lower_dict_into_record",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "lower_dict_into_record.unsupported_field_type.1",
        site: "lowering/mod.rs::lower_dict_into_record",
        category: Category::FieldType,
        status: Status::Capped,
        corpus: "",
        reason: "schema/dict field type has no canonical layout in this position",
    },
    LedgerEntry {
        id: "lower_dict_into_record.unsupported_expr.2",
        site: "lowering/mod.rs::lower_dict_into_record",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "lower_dict_into_record.unsupported_field_type.2",
        site: "lowering/mod.rs::lower_dict_into_record",
        category: Category::FieldType,
        status: Status::Capped,
        corpus: "",
        reason: "schema/dict field type has no canonical layout in this position",
    },
    LedgerEntry {
        id: "lower_dict_field_value.unsupported_expr.1",
        site: "lowering/mod.rs::lower_dict_field_value",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "lower_dict_field_value.unsupported_field_type.1",
        site: "lowering/mod.rs::lower_dict_field_value",
        category: Category::FieldType,
        status: Status::Capped,
        corpus: "",
        reason: "schema/dict field type has no canonical layout in this position",
    },
    LedgerEntry {
        id: "lower_dict_field_value.unsupported_field_type.2",
        site: "lowering/mod.rs::lower_dict_field_value",
        category: Category::FieldType,
        status: Status::Capped,
        corpus: "",
        reason: "schema/dict field type has no canonical layout in this position",
    },
    LedgerEntry {
        id: "lower_dict_field_value.unsupported_expr.2",
        site: "lowering/mod.rs::lower_dict_field_value",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "lower_dict_field_value.unsupported_field_type.3",
        site: "lowering/mod.rs::lower_dict_field_value",
        category: Category::FieldType,
        status: Status::Capped,
        corpus: "",
        reason: "schema/dict field type has no canonical layout in this position",
    },
    LedgerEntry {
        id: "lower_dict_default.missing_field_no_default",
        site: "lowering/mod.rs::lower_dict_default",
        category: Category::FieldType,
        status: Status::Capped,
        corpus: "",
        reason: "branded dict omits a field that has no schema-side default",
    },
    LedgerEntry {
        id: "lower_variable.unsupported_expr.1",
        site: "lowering/mod.rs::lower_variable",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "lower_variable.unsupported_expr.2",
        site: "lowering/mod.rs::lower_variable",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "lower_variable.unresolved_variable.1",
        site: "lowering/mod.rs::lower_variable",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "identifier resolves to no in-scope binding at lowering time",
    },
    LedgerEntry {
        id: "lower_variable.unresolved_variable.2",
        site: "lowering/mod.rs::lower_variable",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "identifier resolves to no in-scope binding at lowering time",
    },
    LedgerEntry {
        id: "lower_variable.unsupported_expr.3",
        site: "lowering/mod.rs::lower_variable",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "lower_variable.unsupported_expr.4",
        site: "lowering/mod.rs::lower_variable",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "lower_variable.unsupported_expr.5",
        site: "lowering/mod.rs::lower_variable",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "lower_variable.unsupported_expr.6",
        site: "lowering/mod.rs::lower_variable",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "lower_variable.unsupported_expr.7",
        site: "lowering/mod.rs::lower_variable",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "lower_variable.unsupported_expr.8",
        site: "lowering/mod.rs::lower_variable",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "lower_variable.unsupported_field_type",
        site: "lowering/mod.rs::lower_variable",
        category: Category::FieldType,
        status: Status::Capped,
        corpus: "",
        reason: "schema/dict field type has no canonical layout in this position",
    },
    LedgerEntry {
        id: "lower_variable.unsupported_expr.9",
        site: "lowering/mod.rs::lower_variable",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "lower_variable.unsupported_expr.10",
        site: "lowering/mod.rs::lower_variable",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "method_signature_ir_types.unsupported_type_in_main.1",
        site: "lowering/mod.rs::method_signature_ir_types",
        category: Category::MainSignatureType,
        status: Status::Capped,
        corpus: "",
        reason: "#main param/return type outside the buffer-protocol decode envelope",
    },
    LedgerEntry {
        id: "method_signature_ir_types.unsupported_type_in_main.2",
        site: "lowering/mod.rs::method_signature_ir_types",
        category: Category::MainSignatureType,
        status: Status::Capped,
        corpus: "",
        reason: "#main param/return type outside the buffer-protocol decode envelope",
    },
    LedgerEntry {
        id: "method_signature_ir_types.unsupported_type_in_main.3",
        site: "lowering/mod.rs::method_signature_ir_types",
        category: Category::MainSignatureType,
        status: Status::Capped,
        corpus: "",
        reason: "#main param/return type outside the buffer-protocol decode envelope",
    },
    LedgerEntry {
        id: "lower_one_method.unsupported_expr.1",
        site: "lowering/mod.rs::lower_one_method",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "lower_one_method.unsupported_expr.2",
        site: "lowering/mod.rs::lower_one_method",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "lower_one_method.unsupported_type_in_main",
        site: "lowering/mod.rs::lower_one_method",
        category: Category::MainSignatureType,
        status: Status::Capped,
        corpus: "",
        reason: "#main param/return type outside the buffer-protocol decode envelope",
    },
    LedgerEntry {
        id: "try_lower_materialized_list_reduce.unresolved_variable",
        site: "lowering/peephole.rs::try_lower_materialized_list_reduce",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "identifier resolves to no in-scope binding at lowering time",
    },
    LedgerEntry {
        id: "try_lower_materialized_list_reduce.unsupported_expr.1",
        site: "lowering/peephole.rs::try_lower_materialized_list_reduce",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "try_lower_materialized_list_reduce.unsupported_expr.2",
        site: "lowering/peephole.rs::try_lower_materialized_list_reduce",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "try_lower_materialized_list_reduce.unsupported_expr.3",
        site: "lowering/peephole.rs::try_lower_materialized_list_reduce",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "combine_operator_to_op.unsupported_expr",
        site: "lowering/peephole.rs::combine_operator_to_op",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "try_lower_list_filter.unknown_stdlib_method.1",
        site: "lowering/peephole.rs::try_lower_list_filter",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "method/function name + arity matches no stdlib signature",
    },
    LedgerEntry {
        id: "try_lower_list_filter.unknown_stdlib_method.2",
        site: "lowering/peephole.rs::try_lower_list_filter",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "method/function name + arity matches no stdlib signature",
    },
    LedgerEntry {
        id: "try_lower_list_filter.unsupported_expr",
        site: "lowering/peephole.rs::try_lower_list_filter",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "emit_list_int_hof_call.unknown_stdlib_method.1",
        site: "lowering/peephole.rs::emit_list_int_hof_call",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "internal guard: bundled list_int_map/filter slot missing from registry",
    },
    LedgerEntry {
        id: "emit_list_int_hof_call.unknown_stdlib_method.2",
        site: "lowering/peephole.rs::emit_list_int_hof_call",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "internal guard: bundled list_int_map/filter metadata missing from registry",
    },
    LedgerEntry {
        id: "emit_list_int_hof_call.unsupported_expr",
        site: "lowering/peephole.rs::emit_list_int_hof_call",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "internal guard: list_int_map/filter closure arg signature missing",
    },
    LedgerEntry {
        id: "emit_list_int_fold_call.unknown_stdlib_method.1",
        site: "lowering/peephole.rs::emit_list_int_fold_call",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "internal guard: bundled list_int_fold slot missing from registry",
    },
    LedgerEntry {
        id: "emit_list_int_fold_call.unknown_stdlib_method.2",
        site: "lowering/peephole.rs::emit_list_int_fold_call",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "internal guard: bundled list_int_fold metadata missing from registry",
    },
    LedgerEntry {
        id: "emit_list_int_fold_call.unsupported_expr.1",
        site: "lowering/peephole.rs::emit_list_int_fold_call",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "_list_reduce init expression is not Int-typed; only Int folds are lowered",
    },
    LedgerEntry {
        id: "emit_list_int_fold_call.unsupported_expr.2",
        site: "lowering/peephole.rs::emit_list_int_fold_call",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "internal guard: list_int_fold closure arg signature missing",
    },
    LedgerEntry {
        id: "lower_comprehension.unsupported_expr.1",
        site: "lowering/mod.rs::lower_comprehension",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "comprehension iterable does not lower to a List<Int> in the AOT envelope",
    },
    LedgerEntry {
        id: "lower_comprehension.unsupported_expr.2",
        site: "lowering/mod.rs::lower_comprehension",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "internal guard: list_int_map/filter closure arg signature missing",
    },
    LedgerEntry {
        id: "lower_comprehension.unknown_stdlib_method.1",
        site: "lowering/mod.rs::lower_comprehension",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "internal guard: bundled list_int_map/filter slot missing from registry",
    },
    LedgerEntry {
        id: "lower_comprehension.unknown_stdlib_method.2",
        site: "lowering/mod.rs::lower_comprehension",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "internal guard: bundled list_int_map/filter metadata missing from registry",
    },
    LedgerEntry {
        id: "try_lower_list_sum_value.unknown_stdlib_method.1",
        site: "lowering/peephole.rs::try_lower_list_sum_value",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "method/function name + arity matches no stdlib signature",
    },
    LedgerEntry {
        id: "try_lower_list_sum_value.unknown_stdlib_method.2",
        site: "lowering/peephole.rs::try_lower_list_sum_value",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "method/function name + arity matches no stdlib signature",
    },
    LedgerEntry {
        id: "emit_list_float_literal_materialize.unsupported_expr.1",
        site: "lowering/peephole.rs::emit_list_float_literal_materialize",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "emit_list_float_literal_materialize.unsupported_expr.2",
        site: "lowering/peephole.rs::emit_list_float_literal_materialize",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "emit_list_float_literal_materialize.unsupported_expr.3",
        site: "lowering/peephole.rs::emit_list_float_literal_materialize",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "emit_list_float_literal_materialize.unsupported_expr.4",
        site: "lowering/peephole.rs::emit_list_float_literal_materialize",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "emit_list_int_literal_materialize.unsupported_expr.1",
        site: "lowering/peephole.rs::emit_list_int_literal_materialize",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "emit_list_int_literal_materialize.unsupported_expr.2",
        site: "lowering/peephole.rs::emit_list_int_literal_materialize",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "emit_list_int_literal_materialize.unsupported_expr.3",
        site: "lowering/peephole.rs::emit_list_int_literal_materialize",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "emit_list_int_literal_materialize.unsupported_expr.4",
        site: "lowering/peephole.rs::emit_list_int_literal_materialize",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "probe_expr_ir_ty.unsupported_expr",
        site: "lowering/peephole.rs::probe_expr_ir_ty",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "emit_list_value_materialize.unsupported_expr.1",
        site: "lowering/peephole.rs::emit_list_value_materialize",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "emit_list_value_materialize.unsupported_expr.2",
        site: "lowering/peephole.rs::emit_list_value_materialize",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "emit_list_value_materialize.unsupported_expr.3",
        site: "lowering/peephole.rs::emit_list_value_materialize",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "emit_list_value_materialize.unsupported_expr.4",
        site: "lowering/peephole.rs::emit_list_value_materialize",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "emit_range_pipeline_loop.unsupported_expr.1",
        site: "lowering/peephole.rs::emit_range_pipeline_loop",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "emit_range_pipeline_loop.unsupported_expr.2",
        site: "lowering/peephole.rs::emit_range_pipeline_loop",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "emit_range_pipeline_loop.unsupported_expr.3",
        site: "lowering/peephole.rs::emit_range_pipeline_loop",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "emit_range_pipeline_loop.unsupported_expr.4",
        site: "lowering/peephole.rs::emit_range_pipeline_loop",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "emit_range_pipeline_loop.unsupported_expr.5",
        site: "lowering/peephole.rs::emit_range_pipeline_loop",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "emit_range_pipeline_loop.unsupported_expr.6",
        site: "lowering/peephole.rs::emit_range_pipeline_loop",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "emit_range_pipeline_loop.unsupported_expr.7",
        site: "lowering/peephole.rs::emit_range_pipeline_loop",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "emit_range_pipeline_loop.unsupported_expr.8",
        site: "lowering/peephole.rs::emit_range_pipeline_loop",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "resolve_capture.unsupported_closure_capture",
        site: "lowering/closure.rs::resolve_capture",
        category: Category::Closure,
        status: Status::Capped,
        corpus: "",
        reason: "capture type has no static byte layout in the captures struct",
    },
    LedgerEntry {
        id: "lower_closure_as_value.unsupported_expr.1",
        site: "lowering/closure.rs::lower_closure_as_value",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "lower_closure_as_value.unsupported_expr.2",
        site: "lowering/closure.rs::lower_closure_as_value",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "lower_closure_as_value.unsupported_expr.3",
        site: "lowering/closure.rs::lower_closure_as_value",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "expression shape has no IR/codegen lowering path yet",
    },
    LedgerEntry {
        id: "lower_closure_as_value.stdlib_arg_type_mismatch",
        site: "lowering/closure.rs::lower_closure_as_value",
        category: Category::ExprShape,
        status: Status::Capped,
        corpus: "",
        reason: "stdlib call argument type disagrees with the declared signature",
    },
];
